#!/bin/bash
#
# (c) Copyright 2017 by Eugene Ciurana / pr3d4t0r
#
# See:  https://github.com/pr3d4t0r/n1ql-vim-syntax


N1QL_SYNTAX_PROJECT="https://github.com/pr3d4t0r/n1ql-vim-syntax.git"
# MacOS and Linux:
TMP_DIR=$(mktemp -d 2> /dev/null || mktemp -d -t 'n1ql')
USER_VIM="$HOME/.vim"


function die {
    if [[ -z "$2" ]]
    then
        exitCode=99
    else
        exitCode="$2"
    fi

    echo "$1"
    exit "$exitCode"
} # die


function assertVimDirExists {
    [[ ! -d "$HOME/.vim" ]] && die "$HOME/.vim directory missing; create it to continue" 1
} # assertVimDirExists


function setup {
    rm -Rf "$TMP_DIR"
    mkdir -p "$TMP_DIR"
} # setup


function cloneProject {
    git clone "$N1QL_SYNTAX_PROJECT" "$TMP_DIR"
} # cloneProject


function _cleanCopy {
    file="$1"

    sourceFile="$2/$file"
    targetFile="$3/$file"

    # Always overrides - no check?  Suggestions?
    rm -f "$targetFile"

    cp -vf "$sourceFile" "$targetFile"
} # _cleanCopy


function installSyntaxFiles {
    vimSyntax="$USER_VIM/syntax"
    vimFileDetection="$USER_VIM/ftdetect"
    vimDocs="$USER_VIM/doc"
    
    originSyntax="$TMP_DIR/syntax"
    originFileDetection="$TMP_DIR/ftdetect"
    originDocs="$TMP_DIR/doc"

    _cleanCopy n1ql.vim "$originSyntax" "$vimSyntax"
    _cleanCopy n1ql.vim "$originFileDetection" "$vimFileDetection"
    _cleanCopy n1ql.txt "$originDocs" "$vimDocs"
} # installSyntaxFiles


function notify {
    printf "N1QL Vim syntax files installed in $USER_VIM\n\n"

    [[ -n $(which tree) ]] && tree -L 2 -I "autoload*|snippets*|include*|lib*|nerdtree*|*plugin*" -P "n1ql.*" "$USER_VIM"
} # notify

function cleanUp {
    rm -Rf "$TMP_DIR"
} # cleanUp


# *** main ***

assertVimDirExists
setup
cloneProject
installSyntaxFiles
notify
cleanUp

